CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	email TEXT NOT NULL UNIQUE,
	password_hash TEXT NOT NULL,
	salt TEXT NOT NULL,
	included_cities TEXT,
	created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS sessions (
	id TEXT PRIMARY KEY,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	expires_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS excluded_areas (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	area_name TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 청약홈 APT 분양정보(getAPTLttotPblancDetail) 일일 배치 수집 결과.
-- 컬럼명은 API 응답 필드명을 그대로 사용해 apt-detail.html의 렌더링 로직을 그대로 재사용한다.
CREATE TABLE IF NOT EXISTS apt_listings (
	HOUSE_MANAGE_NO TEXT NOT NULL,
	PBLANC_NO TEXT NOT NULL,
	HOUSE_NM TEXT, HOUSE_SECD TEXT, HOUSE_SECD_NM TEXT,
	HOUSE_DTL_SECD TEXT, HOUSE_DTL_SECD_NM TEXT,
	RENT_SECD TEXT, RENT_SECD_NM TEXT,
	SUBSCRPT_AREA_CODE TEXT, SUBSCRPT_AREA_CODE_NM TEXT,
	HSSPLY_ZIP TEXT, HSSPLY_ADRES TEXT, TOT_SUPLY_HSHLDCO TEXT,
	RCRIT_PBLANC_DE TEXT, NSPRC_NM TEXT,
	RCEPT_BGNDE TEXT, RCEPT_ENDDE TEXT,
	SPSPLY_RCEPT_BGNDE TEXT, SPSPLY_RCEPT_ENDDE TEXT,
	GNRL_RNK1_CRSPAREA_RCPTDE TEXT, GNRL_RNK1_CRSPAREA_ENDDE TEXT,
	GNRL_RNK1_ETC_GG_RCPTDE TEXT, GNRL_RNK1_ETC_GG_ENDDE TEXT,
	GNRL_RNK1_ETC_AREA_RCPTDE TEXT, GNRL_RNK1_ETC_AREA_ENDDE TEXT,
	GNRL_RNK2_CRSPAREA_RCPTDE TEXT, GNRL_RNK2_CRSPAREA_ENDDE TEXT,
	GNRL_RNK2_ETC_GG_RCPTDE TEXT, GNRL_RNK2_ETC_GG_ENDDE TEXT,
	GNRL_RNK2_ETC_AREA_RCPTDE TEXT, GNRL_RNK2_ETC_AREA_ENDDE TEXT,
	PRZWNER_PRESNATN_DE TEXT, CNTRCT_CNCLS_BGNDE TEXT, CNTRCT_CNCLS_ENDDE TEXT,
	HMPG_ADRES TEXT, CNSTRCT_ENTRPS_NM TEXT, MDHS_TELNO TEXT, BSNS_MBY_NM TEXT,
	MVN_PREARNGE_YM TEXT,
	SPECLT_RDN_EARTH_AT TEXT, MDAT_TRGET_AREA_SECD TEXT, PARCPRC_ULS_AT TEXT,
	IMPRMN_BSNS_AT TEXT, PUBLIC_HOUSE_EARTH_AT TEXT, LRSCL_BLDLND_AT TEXT,
	NPLN_PRVOPR_PUBLIC_HOUSE_AT TEXT, PUBLIC_HOUSE_SPCLW_APPLC_AT TEXT,
	PBLANC_URL TEXT,
	fetched_at TEXT NOT NULL DEFAULT (datetime('now')),
	PRIMARY KEY (HOUSE_MANAGE_NO, PBLANC_NO)
);

CREATE INDEX IF NOT EXISTS idx_apt_listings_area_end ON apt_listings (SUBSCRPT_AREA_CODE_NM, RCEPT_ENDDE);
CREATE INDEX IF NOT EXISTS idx_apt_listings_pblanc_de ON apt_listings (RCRIT_PBLANC_DE);

-- 오피스텔/도시형/민간임대/생활숙박시설 분양정보(getUrbtyOfctlLttotPblancDetail) 일일 배치 수집 결과.
-- 컬럼명은 API 응답 필드명을 그대로 사용 (실제 응답으로 검증됨 - 문서 예시에는 SUBSCRPT_AREA_CODE_NM이 누락돼 있었음).
CREATE TABLE IF NOT EXISTS urbty_listings (
	HOUSE_MANAGE_NO TEXT NOT NULL,
	PBLANC_NO TEXT NOT NULL,
	HOUSE_NM TEXT, HOUSE_SECD TEXT, HOUSE_SECD_NM TEXT,
	HOUSE_DTL_SECD TEXT, HOUSE_DTL_SECD_NM TEXT, SEARCH_HOUSE_SECD TEXT,
	SUBSCRPT_AREA_CODE TEXT, SUBSCRPT_AREA_CODE_NM TEXT,
	HSSPLY_ZIP TEXT, HSSPLY_ADRES TEXT, TOT_SUPLY_HSHLDCO TEXT,
	RCRIT_PBLANC_DE TEXT, NSPRC_NM TEXT,
	SUBSCRPT_RCEPT_BGNDE TEXT, SUBSCRPT_RCEPT_ENDDE TEXT,
	PRZWNER_PRESNATN_DE TEXT, CNTRCT_CNCLS_BGNDE TEXT, CNTRCT_CNCLS_ENDDE TEXT,
	HMPG_ADRES TEXT, BSNS_MBY_NM TEXT, MDHS_TELNO TEXT, MVN_PREARNGE_YM TEXT,
	PBLANC_URL TEXT,
	fetched_at TEXT NOT NULL DEFAULT (datetime('now')),
	PRIMARY KEY (HOUSE_MANAGE_NO, PBLANC_NO)
);

CREATE INDEX IF NOT EXISTS idx_urbty_listings_area_end ON urbty_listings (SUBSCRPT_AREA_CODE_NM, SUBSCRPT_RCEPT_ENDDE);
CREATE INDEX IF NOT EXISTS idx_urbty_listings_pblanc_de ON urbty_listings (RCRIT_PBLANC_DE);

-- APT 잔여세대 분양정보(getRemndrLttotPblancDetail) 일일 배치 수집 결과.
-- 원본 API가 YYYY-MM-DD 형식을 쓰므로 별도 날짜 정규화 없이 그대로 저장한다.
-- 마감판단은 SUBSCRPT_RCEPT_ENDDE, 없으면 GNRL_RCEPT_ENDDE로 대체(COALESCE)한다.
CREATE TABLE IF NOT EXISTS remndr_listings (
	HOUSE_MANAGE_NO TEXT NOT NULL,
	PBLANC_NO TEXT NOT NULL,
	HOUSE_NM TEXT, HOUSE_SECD TEXT, HOUSE_SECD_NM TEXT,
	SUBSCRPT_AREA_CODE TEXT, SUBSCRPT_AREA_CODE_NM TEXT,
	HSSPLY_ZIP TEXT, HSSPLY_ADRES TEXT, TOT_SUPLY_HSHLDCO TEXT,
	RCRIT_PBLANC_DE TEXT, NSPRC_NM TEXT,
	SUBSCRPT_RCEPT_BGNDE TEXT, SUBSCRPT_RCEPT_ENDDE TEXT,
	SPSPLY_RCEPT_BGNDE TEXT, SPSPLY_RCEPT_ENDDE TEXT,
	GNRL_RCEPT_BGNDE TEXT, GNRL_RCEPT_ENDDE TEXT,
	PRZWNER_PRESNATN_DE TEXT, CNTRCT_CNCLS_BGNDE TEXT, CNTRCT_CNCLS_ENDDE TEXT,
	HMPG_ADRES TEXT, BSNS_MBY_NM TEXT, MDHS_TELNO TEXT, MVN_PREARNGE_YM TEXT,
	PBLANC_URL TEXT,
	fetched_at TEXT NOT NULL DEFAULT (datetime('now')),
	PRIMARY KEY (HOUSE_MANAGE_NO, PBLANC_NO)
);

CREATE INDEX IF NOT EXISTS idx_remndr_listings_area_end ON remndr_listings (SUBSCRPT_AREA_CODE_NM, SUBSCRPT_RCEPT_ENDDE);
CREATE INDEX IF NOT EXISTS idx_remndr_listings_pblanc_de ON remndr_listings (RCRIT_PBLANC_DE);

-- 공공지원 민간임대 분양정보(getPblPvtRentLttotPblancDetail) 일일 배치 수집 결과.
-- 원본 API가 YYYYMMDD(하이픈 없음) 형식을 쓰므로, 배치 저장 시 YYYY-MM-DD로 정규화해서 넣는다
-- (다른 테이블과 동일한 형식으로 맞춰야 조회 시 date('now') 비교/정렬이 올바르게 동작함).
CREATE TABLE IF NOT EXISTS pblpvtrent_listings (
	HOUSE_MANAGE_NO TEXT NOT NULL,
	PBLANC_NO TEXT NOT NULL,
	HOUSE_NM TEXT, HOUSE_SECD TEXT, HOUSE_SECD_NM TEXT,
	HOUSE_DETAIL_SECD TEXT, HOUSE_DETAIL_SECD_NM TEXT, SEARCH_HOUSE_SECD TEXT,
	SUBSCRPT_AREA_CODE TEXT, SUBSCRPT_AREA_CODE_NM TEXT,
	HSSPLY_ZIP TEXT, HSSPLY_ADRES TEXT, TOT_SUPLY_HSHLDCO TEXT,
	RCRIT_PBLANC_DE TEXT, NSPRC_NM TEXT,
	SUBSCRPT_RCEPT_BGNDE TEXT, SUBSCRPT_RCEPT_ENDDE TEXT,
	PRZWNER_PRESNATN_DE TEXT, CNTRCT_CNCLS_BGNDE TEXT, CNTRCT_CNCLS_ENDDE TEXT,
	HMPG_ADRES TEXT, BSNS_MBY_NM TEXT, MDHS_TELNO TEXT, MVN_PREARNGE_YM TEXT,
	PBLANC_URL TEXT,
	fetched_at TEXT NOT NULL DEFAULT (datetime('now')),
	PRIMARY KEY (HOUSE_MANAGE_NO, PBLANC_NO)
);

CREATE INDEX IF NOT EXISTS idx_pblpvtrent_listings_area_end ON pblpvtrent_listings (SUBSCRPT_AREA_CODE_NM, SUBSCRPT_RCEPT_ENDDE);
CREATE INDEX IF NOT EXISTS idx_pblpvtrent_listings_pblanc_de ON pblpvtrent_listings (RCRIT_PBLANC_DE);

-- 임의공급 분양정보(getOPTLttotPblancDetail) 일일 배치 수집 결과.
-- 원본 API가 YYYYMMDD(하이픈 없음) 형식을 쓰므로 YYYY-MM-DD로 정규화해서 저장한다.
-- 마감판단은 SUBSCRPT_RCEPT_ENDDE, 없으면 GNRL_RCEPT_ENDDE로 대체(COALESCE)한다.
CREATE TABLE IF NOT EXISTS opt_listings (
	HOUSE_MANAGE_NO TEXT NOT NULL,
	PBLANC_NO TEXT NOT NULL,
	HOUSE_NM TEXT, HOUSE_SECD TEXT, HOUSE_SECD_NM TEXT,
	SUBSCRPT_AREA_CODE TEXT, SUBSCRPT_AREA_CODE_NM TEXT,
	HSSPLY_ZIP TEXT, HSSPLY_ADRES TEXT, TOT_SUPLY_HSHLDCO TEXT,
	RCRIT_PBLANC_DE TEXT,
	SUBSCRPT_RCEPT_BGNDE TEXT, SUBSCRPT_RCEPT_ENDDE TEXT,
	SPSPLY_RCEPT_BGNDE TEXT, SPSPLY_RCEPT_ENDDE TEXT,
	GNRL_RCEPT_BGNDE TEXT, GNRL_RCEPT_ENDDE TEXT,
	PRZWNER_PRESNATN_DE TEXT, CNTRCT_CNCLS_BGNDE TEXT, CNTRCT_CNCLS_ENDDE TEXT,
	HMPG_ADRES TEXT, BSNS_MBY_NM TEXT, MDHS_TELNO TEXT, MVN_PREARNGE_YM TEXT,
	PBLANC_URL TEXT,
	fetched_at TEXT NOT NULL DEFAULT (datetime('now')),
	PRIMARY KEY (HOUSE_MANAGE_NO, PBLANC_NO)
);

CREATE INDEX IF NOT EXISTS idx_opt_listings_area_end ON opt_listings (SUBSCRPT_AREA_CODE_NM, SUBSCRPT_RCEPT_ENDDE);
CREATE INDEX IF NOT EXISTS idx_opt_listings_pblanc_de ON opt_listings (RCRIT_PBLANC_DE);

-- 일일 배치(scheduled()) 실행 결과 로그. 타입별로 매 실행마다 한 행씩 남는다.
CREATE TABLE IF NOT EXISTS batch_runs (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	listing_type TEXT NOT NULL,
	status TEXT NOT NULL, -- 'success' | 'failure'
	row_count INTEGER,
	error_message TEXT,
	ran_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_batch_runs_type_ran_at ON batch_runs (listing_type, ran_at);

-- 개인설정의 "포함할 지역"(주소 키워드 기반 - excluded_areas와 반대). 하나라도 등록되어 있으면
-- 공급위치(HSSPLY_ADRES 등)에 그 키워드 중 하나라도 포함된 공고만 조회 결과에 표시된다.
CREATE TABLE IF NOT EXISTS included_areas (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	area_name TEXT NOT NULL,
	created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
